local map = require("./map")
local t = require("../../types")

type Array<T> = t.Array<T>

return function<T>(arr: Array<T>, separator: string?): string
  if #arr == 0 then
    return ""
  end
  -- JS does tostring conversion implicitely but in Lua we need to do that explicitely
  local stringifiedArray = map(arr, function(item)
    return tostring(item)
  end)

  return table.concat(stringifiedArray, separator or ",")
end
